//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AsciiAlphabet
    {
        [Key]
        public int AlphabetId { get; set; }
        public int Ascii { get; set; }
    
        public virtual Alphabet Alphabet { get; set; }
    }
}
