//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class AsciiAlphabet
    {
        [Column(Order = 0), Key]
        public int AlphabetId { get; set; }
        public Nullable<int> Index { get; set; }
        [Column(Order = 1), Key]
        public int Ascii { get; set; }
    }
}
