//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class AsciiResult
    {
        [Column(Order = 0), Key]
        public int AttemptNumber { get; set; }
        [Column(Order = 1), Key]
        public int Ascii { get; set; }
        [Column(Order = 2), Key]
        public int AlphabetResultId { get; set; }
        public Nullable<int> R { get; set; }
        public Nullable<int> G { get; set; }
        public Nullable<int> B { get; set; }
        public Nullable<int> A { get; set; }
    
        public virtual AlphabetResult AlphabetResult { get; set; }
    }
}
